### ISSUE TITLE
--use_homology flag leads to segmentation fault error

### ISSUE THREAD

**Issue by MartinSchmitz95** [meredith705/gfase_wdl#1]
Hello,
I am trying to use the workflow to create an assembly using a gfa file and poreC reads. So I run the following command as given in the readme:
`java -jar $CROMWELL_JAR run workflows/gfase.wdl -i inputs/input.tiny.porec.json`
It works without errors but now I want to set the flag --use_homology. I set the flag inside `/workflows/gfase_tasks/gfase_phase_contacts_with_monte_carlo.wdl ` 
in line 14. However, the workflow gives a segmentation fault error now.
`call-gfasePhaseContactsMC/execution/script: line 41:    64 Segmentation fault      (core dumped) `
How do I successfully create a GFAse assembly with --use_homology flag?

**Comment by rlorigro** [comment]
Hi Martin, sorry for the slow response on this. I would recommend opening issues of this type on the GFAse repository directly, instead of this one, because it is most likely an issue with GFAse source code, not the WDL.

However, I do see that you have used the `input.tiny.porec.json` and I'm guessing something in that file could cause issues with the homology argument. Can you provide more context (more lines of output) from your run? There should be a stderr log that you can look at.

@meredith705 @jmonlong have you by any chance tested the `tiny` inputs JSON using `--homology` ?

**Comment by MartinSchmitz95** [comment]
Hi  Ryan,

One thing to mention is that the file `input.tiny.porec.json` was trying to load the docker image `"jmonlong-gfase:latest"`. Since this image does not seem to be available, I changed it to `"meredith705/gfase:latest"`

The following is the output of the stderr log file (I set both `--use_homology` and `--skip_unzip` but also with only `--use_homology` it already crashes)

```
+ samtools merge -n -@ 46 -o allBams.bam /cromwell-executions/runGFAsePhase/43f6b539-84b9-4ca0-92f2-a9cc4728489e/call-gfaseLinkedRead/RunGfaseLinkedReadmc/2a5a12cc-965c-4ae2-bb08-af2b54119153/call-gfasePhaseContactsMC/inputs/1335897713/test.test_porec.bam
[W::bam_merge_core2] No @HD tag found.
+ echo hi-c phase
+ phase_contacts_with_monte_carlo -i allBams.bam -g /cromwell-executions/runGFAsePhase/43f6b539-84b9-4ca0-92f2-a9cc4728489e/call-gfaseLinkedRead/RunGfaseLinkedReadmc/2a5a12cc-965c-4ae2-bb08-af2b54119153/call-gfasePhaseContactsMC/inputs/-1620284102/test.gfa -o gfase -m 3 -t 46 --use_homology --skip_unzip
[0h 0m 0s] Loading GFA...
No index found, generating .gfai for "/cromwell-executions/runGFAsePhase/43f6b539-84b9-4ca0-92f2-a9cc4728489e/call-gfaseLinkedRead/RunGfaseLinkedReadmc/2a5a12cc-965c-4ae2-bb08-af2b54119153/call-gfasePhaseContactsMC/inputs/-1620284102/test.gfa" ... done
Creating nodes...
Creating edges...
[0h 0m 0s] Writing IDs to file...
[0h 0m 0s] Loading alignments as contact map...
[0h 0m 0s] Finding alts with sequence homology...
Using 122978293824730352 of 18446744073709551615 possible bins, for 6 iterations at a rate of 0.00666667
130000 possible unique kmers in sequence
5200 kmers after downsampling
26000 bins allocated
Beginning iteration: 0
Beginning iteration: 1
Beginning iteration: 2
Beginning iteration: 3
Beginning iteration: 4
Beginning iteration: 5
Aggregating overlap info...
Filtering overlaps...
Sorting...
Found 35 pairs
Aligning 0 pairs
[0h 0m 0s] Done
[0h 0m 0s] Removing self edges...
[0h 0m 0s] Writing contacts to file...
[0h 0m 0s] Optimizing phases...
---- 0 ----
/cromwell-executions/runGFAsePhase/43f6b539-84b9-4ca0-92f2-a9cc4728489e/call-gfaseLinkedRead/RunGfaseLinkedReadmc/2a5a12cc-965c-4ae2-bb08-af2b54119153/call-gfasePhaseContactsMC/execution/script: line 41:    65 Segmentation fault      (core dumped) phase_contacts_with_monte_carlo -i allBams.bam -g /cromwell-executions/runGFAsePhase/43f6b539-84b9-4ca0-92f2-a9cc4728489e/call-gfaseLinkedRead/RunGfaseLinkedReadmc/2a5a12cc-965c-4ae2-bb08-af2b54119153/call-gfasePhaseContactsMC/inputs/-1620284102/test.gfa -o gfase -m 3 -t 46 --use_homology --skip_unzip
```

**Comment by MartinSchmitz95** [comment]
Also, the same error occurs when I use the input:  ` inputs/input.tiny.linked_reads.json`

**Comment by rlorigro** [comment]
Hi Martin, I believe the issue is that there are no homologs detected in the tiny test file. This is indicated by the line that says "aligning 0 pairs". Certainly, a segmentation fault is not the best response to this edge case, but on the other hand, if you want to try this repository out, it might make sense to use a more realistic dataset. Do you have an application in mind? 

I can work on making a more informative error message for this case.

EDIT: I took a look at the test GFA and I believe it should contain some homologs, so I can also spend some time on why they aren't passing the filters during the detection step.

**Comment by rlorigro** [comment]
@meredith705 can confirm which docker image is the correct one

**Comment by meredith705** [comment]
Hello @MartinSchmitz95 and @rlorigro yes the `"meredith705/gfase:latest"` is the correct docker to use. I'll remove the other docker from the test json. 

One thing, if you'd like to add the extra arguments to the WDL there is a `otherPhaseContatcsArguments` input field you can use in the input .json. Instead of altering the WDL. For example: 
`{
  "runGFAsePhase.assemblyGFA": "tiny_test_data/test.gfa",
  "runGFAsePhase.porecFiles": ["tiny_test_data/test_porec.fastq.gz"],
  "runGFAsePhase.gfaseLinkedRead.otherPhaseContactsArugments" : "--use_homology --skip_unzip"
}`

Unfortunately, however, I have gotten the same segmentation fault you report when I add those arguments.

**Comment by MartinSchmitz95** [comment]
> 

Hi Ryan,
thank you for the answer. It makes sense, I did not try a proper dataset yet. Let me check if that resolves the issue.

The first application I want to try is using the tool on HiFiasm graphs. For this can I just take the normal HiFiasm output GFAs, then take the matching HiC or PoreC data and use GFAse with both parameters --use_homology and --skip_unzip?

**Comment by MartinSchmitz95** [comment]
> Hello @MartinSchmitz95 and @rlorigro yes the `"meredith705/gfase:latest"` is the correct docker to use. I'll remove the other docker from the test json.
> 
> One thing, if you'd like to add the extra arguments to the WDL there is a `otherPhaseContatcsArguments` input field you can use in the input .json. Instead of altering the WDL. For example: `{ "runGFAsePhase.assemblyGFA": "tiny_test_data/test.gfa", "runGFAsePhase.porecFiles": ["tiny_test_data/test_porec.fastq.gz"], "runGFAsePhase.gfaseLinkedRead.otherPhaseContactsArugments" : "--use_homology --skip_unzip" }`
> 
> Unfortunately, however, I have gotten the same segmentation fault you report when I add those arguments.

Hello Melissa,

Thank you a lot! I will change the parameters from the input file then.

**Comment by rlorigro** [comment]
> The first application I want to try is using the tool on HiFiasm graphs. For this can I just take the normal HiFiasm output GFAs, then take the matching HiC or PoreC data and use GFAse with both parameters --use_homology and --skip_unzip?

I took a look at the output files (overlaps.csv and alignments.csv) and I saw that the hash similarity of the homologs in the "tiny" input data was less than 70% because it is an old R9 Shasta assembly. So the reason they are being lost is just a result of the arbitrary cutoff I made. The homolog detection code path was essentially designed and tested on HiFi-based assemblies, so for your use case it should work fine. Shasta assemblies don't require de novo homolog detection because their GFAs are annotated already. 

Regardless, the cutoff should be possible to set by the user, so I am working on adding that as an option.

To answer your question more briefly: yes you just need the corresponding data from the same individual/sample and plug it into the WDL with `skip_unzip` and `use_homology`.

**Comment by MartinSchmitz95** [comment]
Perfect, that is good to know.
Thank you Ryan.

**Comment by rlorigro** [comment]
Hi Martin, 

If you would like to play around more with the test dataset, there are now many more parameters available to tune the homology detection. They can be called in the WDL through the "otherPhaseContactsArugments" field. In particular you would probably just want to lower the `--homology_min_hash_similarity` from its default of 0.7 to something that captures all the valid overlaps in your overlaps.csv file.
